import Link from "next/link";
import { Byline } from "@/components/Byline";
import { Faq, type FaqItem } from "@/components/Faq";
import { Figure } from "@/components/Figure";
import { articleImage, articleOgImage, insightImageKey } from "@/lib/articleImages";
import {
  CATEGORY_LABEL,
  categoryPath,
  insightPath,
  type Insight,
  type InsightCategory,
} from "@/lib/data/insights";
import { reviewDate } from "@/lib/format";
import { site } from "@/lib/site";

/**
 * The shell every /insights/ article renders inside, plus the card and browse
 * strip its indexes use.
 *
 * Deliberately not GuideLayout: that component takes a `Programme` and builds
 * the answer-first / key-facts / who-it-suits shape around it, which is right
 * for a page about one programme and wrong for an article about the choice
 * between three. What carries over is the furniture that earns trust — the
 * byline with its review date, the FAQ, the sources block — because for a 45+,
 * scam-alert reader that furniture is the conversion mechanism (SPEC.md §4.3).
 */

export function InsightLayout({
  article,
  sources,
  faq,
  children,
}: {
  article: Insight;
  /** Every figure in the body traces to one of these. Rendered, not optional. */
  sources: { label: string; url: string; verified: string }[];
  faq: FaqItem[];
  children: React.ReactNode;
}) {
  return (
    <article className="space-y-10">
      <ArticleSchema article={article} />

      <nav aria-label="Breadcrumb" className="text-caption text-ink-muted">
        <Link href="/insights/" className="text-forest-700 underline">
          Insights
        </Link>
        <span aria-hidden> › </span>
        <Link
          href={categoryPath(article.category)}
          className="text-forest-700 underline"
        >
          {CATEGORY_LABEL[article.category]}
        </Link>
      </nav>

      <header className="space-y-6">
        <p className="eyebrow">{CATEGORY_LABEL[article.category]}</p>
        <h1 className="text-h1 font-semibold">
          {article.title}
        </h1>
        <p className="border-l-4 border-forest-600 bg-forest-50 py-4 pl-5 pr-4 text-lead leading-relaxed text-forest-900">
          {article.dek}
        </p>
        <p className="text-body-sm text-ink-muted">
          {article.readingMinutes} min read · Published{" "}
          {reviewDate(article.published)}
        </p>
      </header>

      {/* Generated by scripts/article-image.mjs; absent until it has been run for
          this article, and the header above reads correctly without it. */}
      <Hero article={article} />

      <Byline lastVerified={article.reviewed} />

      {/* The prose. Sizing lives here rather than on each child so an article
          body stays plain semantic markup and inherits the reading measure. */}
      <div className="space-y-7 text-body-sm leading-[1.75]">{children}</div>

      <Faq items={faq} />

      <Sources sources={sources} />

      <Handoff article={article} />
    </article>
  );
}

function Hero({ article }: { article: Insight }) {
  const image = articleImage(insightImageKey(article.category, article.slug));
  if (!image) return null;
  return <Figure image={image} aspect="aspect-[16/9]" priority />;
}

/**
 * The article's own social card, spread into an article page's `openGraph`.
 * Falls back to nothing, which leaves the site-wide card from the root layout.
 */
export function insightOpenGraphImages(article: Pick<Insight, "category" | "slug" | "title">) {
  const og = articleOgImage(insightImageKey(article.category, article.slug));
  return og
    ? { images: [{ url: og, width: 1200, height: 630, alt: article.title }] }
    : {};
}

/** A body heading. Articles use these instead of raw h2s so spacing is uniform. */
export function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="pt-4 text-h2 font-semibold leading-snug text-forest-900">
      {children}
    </h2>
  );
}

export function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="pt-2 text-h3 font-semibold leading-snug text-forest-700">
      {children}
    </h3>
  );
}

/**
 * The sentence the reader is meant to nod at. One per article at most — its
 * whole effect comes from being the only thing on the page that looks like this.
 */
export function Pullquote({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-display accent-text border-l-4 border-forest-300 pl-6 text-h3 font-medium italic leading-snug">
      {children}
    </p>
  );
}

/**
 * Every figure traces to an official document, with the date it was checked.
 * This block is the reason the page is citable — by a reader and by a model.
 */
function Sources({
  sources,
}: {
  sources: { label: string; url: string; verified: string }[];
}) {
  return (
    <section className="rounded-xl bg-sand-100 px-6 py-6">
      <h2 className="text-lead font-semibold text-forest-900">Sources</h2>
      <p className="mt-2 text-caption text-ink-muted">
        Every figure above comes from an official government document. Where an
        official source is silent, this site says so rather than fill the gap —
        see{" "}
        <Link href="/editorial-policy/" className="text-forest-700 underline">
          how we research and date pages
        </Link>
        .
      </p>
      <ul className="mt-4 space-y-2 text-caption">
        {sources.map((s) => (
          <li key={s.url}>
            <a
              href={s.url}
              className="text-forest-700 underline"
              rel="nofollow noopener"
              target="_blank"
            >
              {s.label}
            </a>
            <span className="text-ink-muted">
              {" "}
              — checked {reviewDate(s.verified)}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
}

/** Never end on a full stop. The article answers a question; this asks the next one. */
function Handoff({ article }: { article: Insight }) {
  return (
    <p className="rounded-xl bg-forest-900 px-6 py-6 text-sand-50">
      This is a comparison, not advice on your own case. Read{" "}
      {article.relatedGuides.map((g, i) => (
        <span key={g.path}>
          {i > 0 && (i === article.relatedGuides.length - 1 ? " or " : ", ")}
          <Link href={g.path} className="font-semibold underline">
            {g.title}
          </Link>
        </span>
      ))}
      , or{" "}
      <Link href="/tools/eligibility/" className="font-semibold underline">
        run the eligibility checker
      </Link>{" "}
      against your own numbers.
    </p>
  );
}

function ArticleSchema({ article }: { article: Insight }) {
  const url = `${site.url}${insightPath(article)}`;
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    description: article.dek,
    url,
    datePublished: article.published,
    dateModified: article.reviewed,
    author: {
      "@type": "Person",
      name: "Jason Yap",
      jobTitle: "Managing Director, MYPVIP",
      url: `${site.url}/about/`,
    },
    publisher: { "@type": "Organization", name: site.name, url: site.url },
    // Absolute, and only when it exists — Google's article rich result wants an
    // image and ignores a relative path rather than resolving it.
    ...(articleOgImage(insightImageKey(article.category, article.slug)) && {
      image: [
        `${site.url}${articleOgImage(insightImageKey(article.category, article.slug))}`,
      ],
    }),
    isPartOf: {
      "@type": "WebPage",
      url: `${site.url}${categoryPath(article.category)}`,
      name: CATEGORY_LABEL[article.category],
    },
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function InsightCard({
  article,
  showCategory = true,
}: {
  article: Insight;
  showCategory?: boolean;
}) {
  return (
    <Link
      href={insightPath(article)}
      className="card-outline block px-6 py-6 transition-colors hover:border-forest-300"
    >
      {showCategory && (
        <p className="eyebrow">{CATEGORY_LABEL[article.category]}</p>
      )}
      <h3 className="mt-2 text-h3 font-semibold leading-snug text-forest-900">
        {article.title}
      </h3>
      <p className="mt-3 text-body-sm leading-relaxed text-ink">{article.dek}</p>
      <p className="mt-4 text-caption text-ink-muted">
        {article.readingMinutes} min read · Reviewed{" "}
        {reviewDate(article.reviewed)}
      </p>
    </Link>
  );
}

/** Browse-by-category strip. Only ever renders categories that have a page. */
export function InsightStrip({
  categories,
  current,
}: {
  categories: { category: InsightCategory; articles: Insight[] }[];
  current?: InsightCategory;
}) {
  if (categories.length === 0) return null;
  return (
    <nav aria-label="Browse by category" className="flex flex-wrap gap-3">
      {categories.map(({ category, articles }) => {
        const isCurrent = category === current;
        return (
          <Link
            key={category}
            href={categoryPath(category)}
            aria-current={isCurrent ? "page" : undefined}
            className={
              isCurrent
                ? "rounded-full bg-forest-900 px-4 py-2 text-caption font-semibold text-sand-50"
                : "rounded-full border border-sand-200 px-4 py-2 text-caption text-forest-700 transition-colors hover:border-forest-300"
            }
          >
            {CATEGORY_LABEL[category]}
            <span className="text-ink-muted"> ({articles.length})</span>
          </Link>
        );
      })}
    </nav>
  );
}
