import Link from "next/link";
import { Byline } from "@/components/Byline";
import { Faq, type FaqItem } from "@/components/Faq";
import { Figure } from "@/components/Figure";
import { articleImage, articleOgImage, insightImageKey } from "@/lib/articleImages";
import {
  categoryPath,
  insightPath,
  type Insight,
  type InsightCategory,
} from "@/lib/data/insights";
import { reviewDate } from "@/lib/format";
import { defaultLocale, htmlLang, localeUrl, type Locale } from "@/lib/i18n";
import { site } from "@/lib/site";
import { getUi } from "@/lib/ui";

/**
 * The shell every /insights/ article renders inside, plus the card and browse
 * strip its indexes use.
 *
 * Deliberately not GuideLayout: that component takes a `Programme` and builds
 * the answer-first / key-facts / who-it-suits shape around it, which is right
 * for a page about one programme and wrong for an article about the choice
 * between three. What carries over is the furniture that earns trust — the
 * byline with its review date, the FAQ, the sources block — because for a 45+,
 * scam-alert reader that furniture is the conversion mechanism (SPEC.md §4.3).
 *
 * `locale` defaults to English so the apex renders exactly as it did before the
 * translated trees existed. Hrefs stay bare paths in every locale: one locale is
 * one hostname, so `/insights/<cat>/<slug>/` resolves against whichever host the
 * reader is on, and a translated index only ever lists articles that exist in
 * its own tree.
 */

export function InsightLayout({
  article,
  sources,
  faq,
  children,
  locale = defaultLocale,
}: {
  article: Insight;
  /** Every figure in the body traces to one of these. Rendered, not optional. */
  sources: { label: string; url: string; verified: string }[];
  faq: FaqItem[];
  children: React.ReactNode;
  locale?: Locale;
}) {
  const copy = getUi(locale).insights;

  return (
    <article className="space-y-10">
      <ArticleSchema article={article} locale={locale} />

      <nav aria-label="Breadcrumb" className="text-caption text-ink-muted">
        <Link href="/insights/" className="text-forest-700 underline">
          {copy.article.breadcrumb}
        </Link>
        <span aria-hidden> › </span>
        <Link
          href={categoryPath(article.category)}
          className="text-forest-700 underline"
        >
          {copy.categoryLabel[article.category]}
        </Link>
      </nav>

      <header className="space-y-6">
        <p className="eyebrow">{copy.categoryLabel[article.category]}</p>
        <h1 className="text-h1 font-semibold">
          {article.title}
        </h1>
        <p className="border-l-4 border-forest-600 bg-forest-50 py-4 pl-5 pr-4 text-lead leading-relaxed text-forest-900">
          {article.dek}
        </p>
        <p className="text-body-sm text-ink-muted">
          {copy.article.publishedLine(
            article.readingMinutes,
            reviewDate(article.published, locale),
          )}
        </p>
      </header>

      {/* Generated by scripts/article-image.mjs; absent until it has been run for
          this article, and the header above reads correctly without it. */}
      <Hero article={article} />

      <Byline lastVerified={article.reviewed} locale={locale} />

      {/* The prose. Sizing lives here rather than on each child so an article
          body stays plain semantic markup and inherits the reading measure. */}
      <div className="space-y-7 text-body-sm leading-[1.75]">{children}</div>

      <Faq items={faq} locale={locale} />

      <Sources sources={sources} locale={locale} />

      <Handoff article={article} locale={locale} />
    </article>
  );
}

function Hero({ article }: { article: Insight }) {
  const image = articleImage(insightImageKey(article.category, article.slug));
  if (!image) return null;
  return <Figure image={image} aspect="aspect-[16/9]" priority />;
}

/**
 * The article's own social card, spread into an article page's `openGraph`.
 * Falls back to nothing, which leaves the site-wide card from the root layout.
 */
export function insightOpenGraphImages(article: Pick<Insight, "category" | "slug" | "title">) {
  const og = articleOgImage(insightImageKey(article.category, article.slug));
  return og
    ? { images: [{ url: og, width: 1200, height: 630, alt: article.title }] }
    : {};
}

/** A body heading. Articles use these instead of raw h2s so spacing is uniform. */
export function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="pt-4 text-h2 font-semibold leading-snug text-forest-900">
      {children}
    </h2>
  );
}

export function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="pt-2 text-h3 font-semibold leading-snug text-forest-700">
      {children}
    </h3>
  );
}

/**
 * The sentence the reader is meant to nod at. One per article at most — its
 * whole effect comes from being the only thing on the page that looks like this.
 */
export function Pullquote({ children }: { children: React.ReactNode }) {
  return (
    <p className="font-display accent-text border-l-4 border-forest-300 pl-6 text-h3 font-medium italic leading-snug">
      {children}
    </p>
  );
}

/**
 * Every figure traces to an official document, with the date it was checked.
 * This block is the reason the page is citable — by a reader and by a model.
 */
function Sources({
  sources,
  locale,
}: {
  sources: { label: string; url: string; verified: string }[];
  locale: Locale;
}) {
  const copy = getUi(locale).insights.article;
  return (
    <section className="rounded-xl bg-sand-100 px-6 py-6">
      <h2 className="text-lead font-semibold text-forest-900">
        {copy.sourcesHeading}
      </h2>
      <p className="mt-2 text-caption text-ink-muted">
        {copy.sourcesNoteBefore}
        <Link href="/editorial-policy/" className="text-forest-700 underline">
          {copy.editorialLink}
        </Link>
        {copy.sourcesNoteAfter}
      </p>
      <ul className="mt-4 space-y-2 text-caption">
        {sources.map((s) => (
          <li key={s.url}>
            <a
              href={s.url}
              className="text-forest-700 underline"
              rel="nofollow noopener"
              target="_blank"
            >
              {s.label}
            </a>
            <span className="text-ink-muted">
              {copy.checkedOn(reviewDate(s.verified, locale))}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
}

/** Never end on a full stop. The article answers a question; this asks the next one. */
function Handoff({ article, locale }: { article: Insight; locale: Locale }) {
  const copy = getUi(locale).insights.article;
  return (
    <p className="rounded-xl bg-forest-900 px-6 py-6 text-sand-50">
      {copy.handoffBefore}
      {article.relatedGuides.map((g, i) => (
        <span key={g.path}>
          {i > 0 &&
            (i === article.relatedGuides.length - 1
              ? copy.listLast
              : copy.listSeparator)}
          <Link href={g.path} className="font-semibold underline">
            {g.title}
          </Link>
        </span>
      ))}
      {copy.handoffBetween}
      <Link href="/tools/eligibility/" className="font-semibold underline">
        {copy.eligibilityLink}
      </Link>
      {copy.handoffAfter}
    </p>
  );
}

function ArticleSchema({
  article,
  locale,
}: {
  article: Insight;
  locale: Locale;
}) {
  const copy = getUi(locale).insights;
  const origin = localeUrl("/", locale).replace(/\/$/, "");
  const url = localeUrl(insightPath(article), locale);
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    description: article.dek,
    url,
    inLanguage: htmlLang[locale],
    datePublished: article.published,
    dateModified: article.reviewed,
    author: {
      "@type": "Person",
      name: "Jason Yap",
      jobTitle: getUi(locale).news.article.authorJobTitle,
      url: localeUrl("/about/", locale),
    },
    publisher: { "@type": "Organization", name: site.name, url: site.url },
    // Absolute, and only when it exists — Google's article rich result wants an
    // image and ignores a relative path rather than resolving it.
    ...(articleOgImage(insightImageKey(article.category, article.slug)) && {
      image: [
        `${origin}${articleOgImage(insightImageKey(article.category, article.slug))}`,
      ],
    }),
    isPartOf: {
      "@type": "WebPage",
      url: localeUrl(categoryPath(article.category), locale),
      name: copy.categoryLabel[article.category],
    },
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

export function InsightCard({
  article,
  showCategory = true,
  locale = defaultLocale,
}: {
  article: Insight;
  showCategory?: boolean;
  locale?: Locale;
}) {
  const copy = getUi(locale).insights;
  return (
    <Link
      href={insightPath(article)}
      className="card-outline block px-6 py-6 transition-colors hover:border-forest-300"
    >
      {showCategory && (
        <p className="eyebrow">{copy.categoryLabel[article.category]}</p>
      )}
      <h3 className="mt-2 text-h3 font-semibold leading-snug text-forest-900">
        {article.title}
      </h3>
      <p className="mt-3 text-body-sm leading-relaxed text-ink">{article.dek}</p>
      <p className="mt-4 text-caption text-ink-muted">
        {copy.article.reviewedLine(
          article.readingMinutes,
          reviewDate(article.reviewed, locale),
        )}
      </p>
    </Link>
  );
}

/** Browse-by-category strip. Only ever renders categories that have a page. */
export function InsightStrip({
  categories,
  current,
  locale = defaultLocale,
}: {
  categories: { category: InsightCategory; articles: Insight[] }[];
  current?: InsightCategory;
  locale?: Locale;
}) {
  const copy = getUi(locale).insights;
  if (categories.length === 0) return null;
  return (
    <nav aria-label={copy.browseAria} className="flex flex-wrap gap-3">
      {categories.map(({ category, articles }) => {
        const isCurrent = category === current;
        return (
          <Link
            key={category}
            href={categoryPath(category)}
            aria-current={isCurrent ? "page" : undefined}
            className={
              isCurrent
                ? "rounded-full bg-forest-900 px-4 py-2 text-caption font-semibold text-sand-50"
                : "rounded-full border border-sand-200 px-4 py-2 text-caption text-forest-700 transition-colors hover:border-forest-300"
            }
          >
            {copy.categoryLabel[category]}
            {/* The count has to follow the pill it sits in. `text-ink-muted` was
                unconditional, which put dark grey on the current pill's navy at
                2.6:1 — invisible, and a failure since this component shipped.
                Found by the SPEC §8 sweep, not by looking. CategoryStrip.tsx
                already does it this way; this is the copy that drifted. */}
            <span className={isCurrent ? "text-sand-50/70" : "text-ink-muted"}>
              {" "}
              ({articles.length})
            </span>
          </Link>
        );
      })}
    </nav>
  );
}
