/**
 * The licensed-agent directory (/agents/) — copied from the two official
 * registers, never typed in by hand.
 *
 * `agents.json` is generated by `scripts/import-agents.py` from the snapshots
 * in raw/agents/. To refresh: snapshot both registers, run the import, review
 * what it prints. See wiki/agents.md. Editing the JSON directly breaks the
 * chain back to the government source, which is the directory's whole claim.
 *
 * No ratings, no featured placement. MYPVIP's own companies sit in the
 * alphabetical order like everyone else, and the page discloses the
 * relationship (SPEC.md §1).
 */
import data from "@/lib/data/agents.json";
import { PVIP_TERMINATED } from "@/lib/data/agent-status";

export type AgentProgramme = "mm2h" | "pvip";

/** [from, to], ISO dates, as one register prints a licence's validity. */
export type Validity = [string, string];

export type Mm2hLicence = {
  licence: string;
  office: "HQ" | "Branch";
  address: string;
  state: string;
  phone: string | null;
  /** From mm2h.gov.my — motac.gov.my prints no email. */
  email: string[];
  /** motac.gov.my's register, the current one. Null: not on it. */
  motac: Validity | null;
  /** mm2h.gov.my's table, which lags motac.gov.my. Null: not on it. */
  mm2hgov: Validity | null;
  /** Set when mm2h.gov.my prints a different number for the same licence. */
  mm2hgovLicence?: string;
};

export type PvipAgency = {
  address: string;
  state: string | null;
  phone: string;
  email: string[];
};

/** A differently-named company sharing a contact detail on the registers. */
export type Related = {
  id: string;
  name: string;
  shared: ("email domain" | "phone number" | "office address")[];
};

export type Agent = {
  id: string;
  name: string;
  mm2h: Mm2hLicence[];
  pvip: PvipAgency | null;
  related?: Related[];
};

export const registers: Record<
  AgentProgramme,
  { name: string; publisher: string; source: string; lastVerified: string }
> = {
  mm2h: {
    name: "Licensed MM2H Company register",
    // Cross-checked against MOTAC's other list, on mm2h.gov.my; see `mm2hgov`.
    publisher: "Ministry of Tourism, Arts and Culture (MOTAC)",
    source:
      "https://www.motac.gov.my/en/kategori-semakan-new/licensed-mm2h-company/",
    lastVerified: data.checked,
  },
  pvip: {
    name: "Authorised Malaysia Premium Visa Programme (PVIP) Application Agencies",
    publisher: "Immigration Department of Malaysia",
    source:
      "https://imigresen-online.imi.gov.my/eservices/doc/AUTHORISED_MALAYSIA_PREMIUM_VISA_PROGRAMME_AGENCIES.pdf",
    lastVerified: data.checked,
  },
};

const agents = data.companies as Agent[];

/** Alphabetical, as imported. */
export const agentsFor = (programme: AgentProgramme): Agent[] =>
  agents.filter((a) => (programme === "mm2h" ? a.mm2h.length > 0 : a.pvip));

/**
 * The licences a card shows: head office only. Branch licences (MM2H810/1 …)
 * stay in the data for the drift check but are not listed, at Jason's call
 * (2026-10-01): one office per company is what a reader needs. A company with
 * no HQ licence on the lists falls back to its first licence.
 */
export const mainLicences = (a: Agent): Mm2hLicence[] => {
  const hq = a.mm2h.filter((l) => l.office === "HQ");
  return hq.length ? hq : a.mm2h.slice(0, 1);
};

/** How many companies the register itself lists — mm2h.gov.my-only rows excluded. */
export const registerCount = (programme: AgentProgramme): number =>
  programme === "mm2h"
    ? agents.filter((a) => a.mm2h.some((l) => l.motac)).length
    : agentsFor("pvip").length;

/** The states a programme's agents have offices in, for the filter. */
export const agentStates = (programme: AgentProgramme): string[] =>
  [
    ...new Set(
      agentsFor(programme).flatMap((a) =>
        programme === "mm2h"
          ? mainLicences(a).map((l) => l.state)
          : a.pvip?.state
            ? [a.pvip.state]
            : [],
      ),
    ),
  ].sort();

export const MM2HGOV_SOURCE = "https://www.mm2h.gov.my/agencies";

/**
 * Where a licence stands on `today`.
 *   valid     on motac.gov.my, in date
 *   expiring  on motac.gov.my, expires within 60 days
 *   expired   past its expiry on whichever register lists it
 *   unlisted  in date on mm2h.gov.my but missing from motac.gov.my
 * Computed when the page is built, so the page says "as at" the build date.
 */
export type LicenceStatus = "valid" | "expiring" | "expired" | "unlisted";

export function licenceStatus(l: Mm2hLicence, today: string): LicenceStatus {
  const to = l.motac?.[1] ?? l.mm2hgov![1];
  if (to < today) return "expired";
  if (!l.motac) return "unlisted";
  const soon = new Date(`${today}T00:00:00Z`);
  soon.setUTCDate(soon.getUTCDate() + 60);
  return to <= soon.toISOString().slice(0, 10) ? "expiring" : "valid";
}

/** The company's best licence, for the status filter. */
export function companyStatus(a: Agent, today: string): LicenceStatus {
  const order: LicenceStatus[] = ["valid", "expiring", "unlisted", "expired"];
  return mainLicences(a)
    .map((l) => licenceStatus(l, today))
    .sort((x, y) => order.indexOf(x) - order.indexOf(y))[0];
}

const byId = new Map(agents.map((a) => [a.id, a]));

// A terminated id that matches no company means a re-import renamed it, and
// the status would silently vanish from the page. Fail the build instead.
for (const id of PVIP_TERMINATED.ids) {
  if (!byId.get(id)?.pvip) {
    throw new Error(
      `agent-status.ts: "${id}" is not a PVIP agency in agents.json. Re-check the id after a re-import.`,
    );
  }
}

const terminated = new Set<string>(PVIP_TERMINATED.ids);

/** PVIP only: on Immigration's list and active, or reported terminated. */
export type PvipStatus = "active" | "terminated";
export const pvipStatus = (a: Agent): PvipStatus =>
  terminated.has(a.id) ? "terminated" : "active";

/**
 * The filter's two choices, for either register: "current" (valid MM2H
 * licence / active PVIP agency) or "lapsed" (expired or unlisted / terminated).
 */
export function statusGroup(
  a: Agent,
  programme: AgentProgramme,
  today: string,
): "current" | "lapsed" {
  if (programme === "pvip")
    return pvipStatus(a) === "active" ? "current" : "lapsed";
  const s = companyStatus(a, today);
  return s === "valid" || s === "expiring" ? "current" : "lapsed";
}

/** Which list a related company appears on, preferring the current one. */
export function relatedHref(r: Related, current: AgentProgramme): string {
  const a = byId.get(r.id);
  const on = (p: AgentProgramme) =>
    p === "mm2h" ? !!a?.mm2h.length : !!a?.pvip;
  const programme = on(current)
    ? current
    : current === "mm2h"
      ? "pvip"
      : "mm2h";
  return `/agents/${programme}/#${r.id}`;
}
